### PR TITLE
remove .local on vhost settings

### PR DESCRIPTION
**Pull request by tillhess**
The TLD is part of the {DOMAIN}

### CODE REVIEW

**Comment by schmengler** [comment]
Thanks for the PR! The problem is, that this will break compatibility with Windows where NFS is not supported. Can you create separate templates `modman_mac` and `allinone_mac` instead?

**Comment by tillhess** [comment]
Oh sorry, I only want to push those two commits.

**Comment by pschulz** [comment]
Sorry, but I did not get the point where this apache directory directive breaks the compatibility with Windows because of missing NFS support.
Could you please explain it a bit?
To me it just looks like a bug that is fixed with the given commits.

**Comment by schmengler** [comment]
@pschulz  Originally the PR contained more, unrelated commits. Now it's fine.

**Pull request merged**
